# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://glassbreakerbox.github.io/
title: Glass Breaker Box
email: glassbreakerbox@gmail.com
author: GBB Team
description: > # "Write an awesome description for your new site here.
  Glass Breaker Box: the new safety device for public transport.
copyright: 'Copyright &copy; 2017 GBB Inc. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/glassbreakerbox
  - title: email
    url: mailto:glassbreakerbox@gmail.com

